# Generated by Django 5.2.13 on 2026-04-15 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=255)),
                ('key', models.CharField(help_text='A short, unique identifier for the project', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project goals and scope')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who created or manages the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sprint', max_length=100)),
                ('goal', models.TextField(blank=True, help_text='The main objective to be achieved during this sprint')),
                ('start_date', models.DateField(blank=True, help_text='The date when the sprint officially starts', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date when the sprint is scheduled to end', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', help_text='Current lifecycle state of the sprint', max_length=20)),
                ('project', models.ForeignKey(help_text='The project this sprint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A concise summary of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description, acceptance criteria or steps to reproduce (for bugs).')),
                ('task_type', models.CharField(choices=[('STORY', 'User Story'), ('TASK', 'Task'), ('BUG', 'Bug')], default='STORY', help_text='The nature of the work item', max_length=10)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('IN_REVIEW', 'In review'), ('DONE', 'Done')], default='BACKLOG', help_text='Current position in workflow', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Importance and urgency of the task', max_length=10)),
                ('story_points', models.PositiveIntegerField(blank=True, help_text='An estimate of the effort required to implement this task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='The user responsible for completing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project to which this task belongs', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.project')),
                ('reporter', models.ForeignKey(help_text='The user who created or reported this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, help_text='The sprint during which this task is planned to be executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scrum.sprint')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
