# Generated by Django 6.0.3 on 2026-05-06 15:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PROGRAMMER', 'Programmer'), ('SCRUM_MASTER', 'Scrum Master'), ('PRODUCT_OWNER', 'Product Owner')], default='PROGRAMMER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=255)),
                ('key', models.CharField(help_text='A short, unique identifier for the project', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project goals and scope')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Programiści w projekcie', related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Product Owner projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('scrum_master', models.ForeignKey(blank=True, help_text='Scrum Master projektu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_master_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sprint', max_length=100)),
                ('goal', models.TextField(blank=True, help_text='The main objective to be achieved during this sprint')),
                ('start_date', models.DateField(blank=True, help_text='The date when the sprint officially starts', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date when the sprint is scheduled to end', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', help_text='Current lifecycle state of the sprint', max_length=20)),
                ('project', models.ForeignKey(help_text='The project this sprint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A concise summary of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description, acceptance criteria or steps to reproduce (for bugs).')),
                ('task_type', models.CharField(choices=[('STORY', 'User Story'), ('TASK', 'Task'), ('BUG', 'Bug')], default='STORY', help_text='The nature of the work item', max_length=10)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('IN_REVIEW', 'In review'), ('DONE', 'Done')], default='BACKLOG', help_text='Current position in workflow', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Importance and urgency of the task', max_length=10)),
                ('story_points', models.PositiveIntegerField(blank=True, help_text='An estimate of the effort required to implement this task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='The user responsible for completing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project to which this task belongs', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.project')),
                ('reporter', models.ForeignKey(help_text='The user who created or reported this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, help_text='The sprint during which this task is planned to be executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scrum.sprint')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
