# Generated by Django 5.2.13 on 2026-05-06 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCT_OWNER', 'Product owner'), ('SCRUM_MASTER', 'Scrum master'), ('PROGRAMMER', 'Programmer')], default='PROGRAMMER', help_text='User role within project context', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project where this user has assigned role', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scrum.project')),
                ('user', models.ForeignKey(help_text='User assigned to a project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project membership',
                'verbose_name_plural': 'Project memberships',
                'ordering': ['project_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership')],
            },
        ),
    ]
