name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: /bin/true
