name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - run: /bin/true
