name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: |
          cd backend
          python3 -m pip install -r requirements.txt
          python3 manage.py test
  build-docker:
    name: Build Docker Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: cp .env.example .env
      - run: docker compose build
